#!/usr/bin/env python3
"""
Stage 5 (data) — generate passage-grounded NATIVE Korean SFT data from the BASE model.

After Stage 4 the model is a *base* model (completion, not instructions). We use
FEW-SHOT in-context learning: show it native exemplars of the target pattern, append
a real Korean passage, let it continue. The answer is grounded because the passage
sits in the context window.

Supported task types (each has a matching exemplars_<task>.json):
  qa              — single question + answer
  reasoned_qa     — question + multi-step (chain-of-thought) answer
  multi_qa        — 3 question-answer pairs per passage (denser SFT data)
  summary         — abstractive summary
  title           — a single headline
  fact_extraction — bullet-list of key facts
  explain_simply  — passage rewritten in simple Korean
  outline         — hierarchical outline
  definition      — define a given term grounded on the passage

Diversity axes — sweep these to multiply per-passage data and let the SFT model
learn explicit register/audience following:

  --exemplars exemplars_<task>_<register>.json     register variation
       (합쇼체 / 해요체 / 문어체 — pick the file; behavior is exemplar-driven)

  --audience  {어린이, 중고급중학교생, 일반, 전문가, mixed}
       audience variation (instruction-driven): prepends an instruction to the
       base-model few-shot header AND prepends a short phrase to the SFT user
       message so the trained model can later follow explicit audience requests.
       'mixed' = no injection (legacy / default behavior).

Filters: language-ID (Hangul fraction) + faithfulness (content-word overlap, with
Korean particles stripped so 조선은/조선이/조선을 count as the same word; skipped for
`title`). For stricter filtering, run output through 05_sft/faithfulness_scorer.py,
05_sft/register_consistency.py, and 05_sft/translationese_scorer.py.
"""
import argparse, json, re, unicodedata

DELIM = "\n---\n"

# Task spec: ordered exemplar field labels + which input keys fill the leading fields.
# All non-input fields are generated by the model (the first one is the cut point).
TASKS = {
    "qa":              {"labels": ["단락", "질문", "답"],          "inputs": ["passage"]},
    "reasoned_qa":     {"labels": ["단락", "질문", "풀이와 답"],     "inputs": ["passage"]},
    "multi_qa":        {"labels": ["단락", "질문-답"],             "inputs": ["passage"]},
    "summary":         {"labels": ["단락", "요약"],                "inputs": ["passage"]},
    "title":           {"labels": ["단락", "제목"],                "inputs": ["passage"]},
    "fact_extraction": {"labels": ["단락", "핵심사실"],            "inputs": ["passage"]},
    "explain_simply":  {"labels": ["단락", "쉬운 설명"],            "inputs": ["passage"]},
    "outline":         {"labels": ["단락", "개요"],                "inputs": ["passage"]},
    "definition":      {"labels": ["용어", "단락", "정의"],         "inputs": ["term", "passage"]},
}
SKIP_FAITHFUL = {"title"}   # too short for content-word overlap to be meaningful

# Audience axis (Option A — prompt-side instruction injection that stacks on top
# of Option B's register-variant exemplars). Each entry is a (build_prompt header
# instruction, to_chat user-message phrase) pair.
#
# Honest limitation: a base model with weak Korean cannot perfectly follow the
# audience instruction from a single prefix line — the few-shot exemplars don't
# themselves vary by audience. Expect best-effort adherence (~60-80% on a strong
# base, lower on a weak one). Spot-check the output and, if needed, build a
# downstream audience-checker (vocabulary level / sentence length) to drop
# off-audience generations — the analogue of register_consistency.py.
AUDIENCES = {
    "어린이":      ("소학교생도 리해할 수 있게 쉬운 어휘와 짧은 문장으로 작성하시오.",
                    "소학교생도 리해할 수 있게"),
    "중고급중학교생":  ("중·고급중학교생 수준의 어휘와 설명으로 작성하시오.",
                    "중·고급중학교생이 리해할 수 있게"),
    "일반":        ("일반 성인 독자가 리해하기 쉽게 작성하시오.",
                    "일반 성인을 대상으로"),
    "전문가":      ("해당 분야 전문가 수준의 정확한 용어로 작성하시오.",
                    "전문가 수준으로"),
}


# ---------------------------------------------------------------------------
# PURE, TESTABLE CORE
# ---------------------------------------------------------------------------
def build_prompt(exemplars, passage, task, term=None, audience_instr=""):
    """Build the few-shot prompt for the base model. If audience_instr is given,
    prepend it as a single instruction header above the exemplar block."""
    spec = TASKS[task]
    labels, inputs = spec["labels"], spec["inputs"]
    blocks = ["\n".join(f"{lab}: {ex[lab]}" for lab in labels) for ex in exemplars]
    vals = {"passage": passage, "term": term}
    open_parts = []
    for i, lab in enumerate(labels):
        if i < len(inputs):
            open_parts.append(f"{lab}: {vals[inputs[i]]}")
        else:
            open_parts.append(f"{lab}:")
            break                          # stop after the first generated label
    body = DELIM.join(blocks + ["\n".join(open_parts)])
    if audience_instr:
        body = f"다음 실례들을 참고하여, {audience_instr}\n\n{body}"
    return body, labels


def _take(completion):
    """Cut completion at the exemplar delimiter or a stray '\\n---'."""
    return completion.split(DELIM)[0].split("\n---")[0].strip()


def parse_completion(completion, task, labels):
    text = _take(completion)
    if not text:
        return None
    if task == "qa":
        m = re.search(rf"(.*?)\n\s*{re.escape(labels[2])}\s*:\s*(.*)", text, re.S)
        return {"question": m.group(1).strip(), "answer": m.group(2).strip()} if m else None
    if task == "reasoned_qa":
        m = re.search(rf"(.*?)\n\s*{re.escape(labels[2])}\s*:\s*(.*)", text, re.S)
        return {"question": m.group(1).strip(), "cot_answer": m.group(2).strip()} if m else None
    if task == "multi_qa":
        pairs = re.findall(r"질문\s*\d*\s*[:.]\s*(.*?)\s*\n\s*답\s*\d*\s*[:.]\s*(.*?)(?=\n\s*질문|\Z)",
                           text, re.S)
        if len(pairs) < 1:
            return None
        return {"qa_pairs": [{"q": q.strip(), "a": a.strip()} for q, a in pairs]}
    return {                                  # single-field tasks
        "summary":         {"summary": text},
        "title":           {"title": text.split("\n")[0].strip()},
        "fact_extraction": {"facts": text},
        "explain_simply":  {"explanation": text},
        "outline":         {"outline": text},
        "definition":      {"definition": text},
    }[task]


def to_chat(passage, parsed, task, term=None, audience_phrase=""):
    """Build the user/assistant chat for SFT. If audience_phrase is given,
    prepend it to the user instruction so the trained model learns to follow
    explicit audience requests at inference."""
    aud = f"{audience_phrase} " if audience_phrase else ""
    if task == "qa":
        user = (f"{aud}다음 단락을 읽고 질문에 답하시오.\n\n"
                f"단락: {passage}\n\n질문: {parsed['question']}")
        asst = parsed["answer"]
    elif task == "reasoned_qa":
        user = (f"{aud}다음 단락을 바탕으로 이 질문을 단계별로 분석하여 대답하시오.\n\n"
                f"단락: {passage}\n\n질문: {parsed['question']}")
        asst = parsed["cot_answer"]
    elif task == "multi_qa":
        user = (f"{aud}다음 단락을 바탕으로 질문-대답 {len(parsed['qa_pairs'])}개를 "
                f"만드시오.\n\n단락: {passage}")
        asst = "\n".join(f"질문 {i+1}: {p['q']}\n대답 {i+1}: {p['a']}"
                         for i, p in enumerate(parsed["qa_pairs"]))
    elif task == "summary":
        user, asst = f"{aud}다음 단락을 요약하시오.\n\n{passage}", parsed["summary"]
    elif task == "title":
        user, asst = f"{aud}다음 단락에 어울리는 제목을 제안하시오.\n\n{passage}", parsed["title"]
    elif task == "fact_extraction":
        user, asst = (f"{aud}다음 단락에서 핵심사실을 뽑아 목록으로 만드시오.\n\n{passage}",
                      parsed["facts"])
    elif task == "explain_simply":
        user, asst = (f"{aud}다음 단락을 쉬운 조선어로 설명하시오.\n\n{passage}",
                      parsed["explanation"])
    elif task == "outline":
        user, asst = (f"{aud}다음 단락의 구조적개요를 작성하시오.\n\n{passage}",
                      parsed["outline"])
    elif task == "definition":
        user, asst = (f"{aud}다음 단락을 바탕으로 '{term}'의 정의를 쓰시오.\n\n{passage}",
                      parsed["definition"])
    return {"messages": [{"role": "user", "content": user},
                         {"role": "assistant", "content": asst}]}


def korean_fraction(s):
    letters = [c for c in s if c.isalpha()]
    if not letters:
        return 0.0
    return sum(1 for c in letters if "HANGUL" in unicodedata.name(c, "")) / len(letters)


# Korean is agglutinative: particles (조사) attach to the noun inside one eojeol,
# so 조선/조선은/조선이/조선을 must reduce to one form before overlap is meaningful.
_PARTICLES = sorted([
    "입니다", "이였다", "이며", "이고", "이다",   # fused copula endings (noun+이다)
    "에서는", "으로는", "에게서", "께서는", "이라고", "이라는",
    "에서", "에게", "께서", "으로", "라고", "부터", "까지", "보다", "처럼",
    "만큼", "마다", "조차", "마저", "밖에", "이나", "든지", "이라", "에는",
    "은", "는", "이", "가", "을", "를", "의", "에", "도", "와", "과", "만",
    "로", "야", "께", "라", "나",
], key=len, reverse=True)


def _strip_particle(w):
    for p in _PARTICLES:
        # only strip if a real (>=2-syllable) stem remains, so 2-char nouns
        # like 정의/회의/수도 are NOT truncated to a single syllable.
        if len(w) - len(p) >= 2 and w.endswith(p):
            return w[: -len(p)]
    return w


_KO_STOP = {"그리고", "그러나", "하지만", "또한", "그래서", "따라서", "즉", "및",
            "등", "것", "수", "더", "매우", "아주", "이", "그", "저", "때문",
            "하다", "있다", "없다", "되다", "이다", "한다", "합니다", "입니다",
            "있습니다", "같은", "위해", "통해", "대한", "대해"}


def _content_words(text):
    out = set()
    for w in text.split():
        w = w.strip("。.,?!\"'()[]{}:;…·")
        w = _strip_particle(w)
        if len(w) >= 2 and korean_fraction(w) > 0.5 and w not in _KO_STOP:
            out.add(w)
    return out


def faithful(answer, passage, thresh=0.1):
    src = _content_words(passage)
    if not src:
        return True
    return len(src & _content_words(answer)) / len(src) > thresh


# ---------------------------------------------------------------------------
# MODEL HOOK + DRIVER
# ---------------------------------------------------------------------------
def generate(prompts, model_path, max_new_tokens=320):
    """Batch-complete with the BASE model. Stop at the exemplar delimiter.

    vLLM:
        from vllm import LLM, SamplingParams
        llm = LLM(model_path)
        sp = SamplingParams(temperature=0.7, top_p=0.9, max_tokens=max_new_tokens,
                            stop=["\\n---\\n", "\\n---"])
        return [o.outputs[0].text for o in llm.generate(prompts, sp)]
    """
    raise NotImplementedError("Connect your base model (vLLM/HF) here.")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", required=True)
    ap.add_argument("--passages", required=True, help="JSONL: {passage, [term]}")
    ap.add_argument("--exemplars", required=True,
                    help="Path to exemplars_<task>[_<register>].json. Use the "
                         "register-tagged file (hapsyo/haeyo/muncheo) when you "
                         "want register-controlled output.")
    ap.add_argument("--task", choices=list(TASKS), default="qa")
    ap.add_argument("--audience", choices=list(AUDIENCES) + ["mixed"], default="mixed",
                    help="Inject an audience instruction into both the base-model "
                         "few-shot header and the SFT user message. 'mixed' = no "
                         "injection (legacy/default). Sweep over the four explicit "
                         "audiences to multiply per-passage diversity.")
    ap.add_argument("--out", required=True)
    ap.add_argument("--min-korean", type=float, default=0.7)
    ap.add_argument("--batch", type=int, default=256)
    args = ap.parse_args()

    exemplars = json.load(open(args.exemplars, encoding="utf-8"))
    rows = [json.loads(l) for l in open(args.passages, encoding="utf-8")]

    audience_instr, audience_phrase = (
        AUDIENCES[args.audience] if args.audience != "mixed" else ("", "")
    )

    prompts, metas = [], []
    for r in rows:
        p, labels = build_prompt(exemplars, r["passage"], args.task, r.get("term"),
                                 audience_instr=audience_instr)
        prompts.append(p); metas.append((r, labels))

    kept = dropped = 0
    with open(args.out, "w", encoding="utf-8") as f:
        for i in range(0, len(prompts), args.batch):
            comps = generate(prompts[i:i + args.batch], args.model)
            for comp, (r, labels) in zip(comps, metas[i:i + args.batch]):
                parsed = parse_completion(comp, args.task, labels)
                if not parsed:
                    dropped += 1; continue
                ans = (parsed.get("answer") or parsed.get("cot_answer")
                       or parsed.get("summary") or parsed.get("title")
                       or parsed.get("facts") or parsed.get("explanation")
                       or parsed.get("outline") or parsed.get("definition")
                       or " ".join(p["a"] for p in parsed.get("qa_pairs", [])))
                if korean_fraction(ans) < args.min_korean:
                    dropped += 1; continue
                if args.task not in SKIP_FAITHFUL and not faithful(ans, r["passage"]):
                    dropped += 1; continue
                f.write(json.dumps(to_chat(r["passage"], parsed, args.task, r.get("term"),
                                           audience_phrase=audience_phrase),
                                   ensure_ascii=False) + "\n")
                kept += 1
    print(f"task={args.task} audience={args.audience}: "
          f"kept {kept:,} | dropped {dropped:,} -> {args.out}")


# ---------------------------------------------------------------------------
def _selftest():
    # qa
    exs = [{"단락": "대동강은 조선의 주요강이다.",
            "질문": "대동강은 무엇인가?", "답": "대동강은 조선의 주요강이다."}]
    passage = "안학궁은 평양에 있다."
    prompt, labels = build_prompt(exs, passage, "qa")
    assert prompt.rstrip().endswith("질문:")
    parsed = parse_completion(" 안학궁은 어디에 있는가?\n답: 안학궁은 평양에 있다.\n---", "qa", labels)
    assert parsed["question"] == "안학궁은 어디에 있는가?" and "평양" in parsed["answer"]

    # reasoned_qa: multi-step CoT answer
    rq_exs = [{"단락": "...", "질문": "왜?",
               "풀이와 답": "단계 1: ...\n단계 2: ...\n따라서 ..."}]
    p, lbl = build_prompt(rq_exs, passage, "reasoned_qa")
    assert p.rstrip().endswith("질문:")
    parsed = parse_completion(" 왜 그런가?\n풀이와 답: 단계 1: 안학궁은 평양에 있다.\n"
                              "단계 2: 유명한 유적이다.\n따라서 맞다.\n---",
                              "reasoned_qa", lbl)
    assert parsed["question"] == "왜 그런가?"
    assert "단계 1" in parsed["cot_answer"] and "따라서" in parsed["cot_answer"]
    chat = to_chat(passage, parsed, "reasoned_qa")
    assert "단계별로" in chat["messages"][0]["content"]
    assert "단계 1" in chat["messages"][1]["content"]

    # multi_qa parsing
    mqa_exs = [{"단락": "...", "질문-답": "질문 1: a?\n답 1: x\n질문 2: b?\n답 2: y"}]
    p, lbl = build_prompt(mqa_exs, passage, "multi_qa")
    assert p.rstrip().endswith("질문-답:")
    parsed = parse_completion("\n질문 1: 어디?\n답 1: 평양\n질문 2: 무엇?\n답 2: 유적\n---",
                              "multi_qa", lbl)
    assert len(parsed["qa_pairs"]) == 2 and parsed["qa_pairs"][1]["a"] == "유적"

    # title (single line, faithfulness skipped)
    t_exs = [{"단락": "...", "제목": "어떤 제목"}]
    p, lbl = build_prompt(t_exs, passage, "title")
    parsed = parse_completion(" 평양의 자랑\n---", "title", lbl)
    assert parsed["title"] == "평양의 자랑"
    assert "title" in SKIP_FAITHFUL

    # definition includes term
    d_exs = [{"용어": "ㄱ", "단락": "...", "정의": "..."}]
    p, lbl = build_prompt(d_exs, passage, "definition", term="유적")
    assert "용어: 유적" in p and p.rstrip().endswith("정의:")

    # filters and chat shape; particle-aware faithfulness
    assert faithful("안학궁은 평양에 있다.", passage)
    assert not faithful("전혀 관련이 없는 문장이다.", passage)
    # particle stripping: 조선은/조선이 reduce to 조선, so they overlap
    assert faithful("조선의 수도", "조선은 동아시아에 있다.")
    chat = to_chat(passage, {"answer": "평양", "question": "어디?"}, "qa")
    assert chat["messages"][1]["content"] == "평양"

    # ----- audience injection (Option A on top of Option B) -----

    # (a) build_prompt prepends a single instruction header above the exemplar block
    instr, phrase = AUDIENCES["어린이"]
    prompt_a, _ = build_prompt(exs, passage, "qa", audience_instr=instr)
    assert prompt_a.startswith("다음 실례들을 참고하여, "), prompt_a[:80]
    assert "소학교생" in prompt_a.split("\n")[0]
    assert prompt_a.rstrip().endswith("질문:")        # exemplar structure preserved

    # (b) to_chat prepends an audience phrase to the SFT user message
    chat_a = to_chat(passage, {"answer": "평양", "question": "어디?"}, "qa",
                     audience_phrase=phrase)
    assert chat_a["messages"][0]["content"].startswith("소학교생도 리해할 수 있게 ")
    assert "질문: 어디?" in chat_a["messages"][0]["content"]

    # (c) empty audience args preserve legacy behavior exactly
    prompt_b, _ = build_prompt(exs, passage, "qa")
    assert not prompt_b.startswith("다음 실례들을 참고하여")
    chat_b = to_chat(passage, {"answer": "평양", "question": "어디?"}, "qa")
    assert chat_b["messages"][0]["content"].startswith("다음 단락을")

    # (d) each of the 4 explicit audiences produces a distinct header and phrase
    seen_headers, seen_phrases = set(), set()
    for aud in AUDIENCES:
        instr, phrase = AUDIENCES[aud]
        p_aud, _ = build_prompt(exs, passage, "qa", audience_instr=instr)
        c_aud = to_chat(passage, {"answer": "x", "question": "y"}, "qa",
                        audience_phrase=phrase)
        seen_headers.add(p_aud.split("\n")[0])
        seen_phrases.add(c_aud["messages"][0]["content"].split("다음 단락")[0].strip())
    assert len(seen_headers) == 4, seen_headers
    assert len(seen_phrases) == 4, seen_phrases

    # (e) audience phrase reaches non-qa tasks too
    chat_sum = to_chat(passage, {"summary": "요약 내용"}, "summary",
                       audience_phrase="전문가 수준으로")
    assert chat_sum["messages"][0]["content"].startswith("전문가 수준으로 ")

    print("PASS all grounded-generation tests (9 tasks: prompt/parse/filters/format "
          "+ audience injection: build_prompt + to_chat + empty-default + 4-way sweep "
          "+ non-qa coverage)")


if __name__ == "__main__":
    import sys
    _selftest() if "--selftest" in sys.argv else main()
